In [2]:
import numpy as np

In [2]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
a = np.linspace(0, 8, 9).reshape(3,3)
b = np.arange(0, 9).reshape(3,3)
a,b

(array([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]]),
 array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]))

In [3]:
a = np.random.rand(5,5)*4
b = np.random.random((5,5))*4
c = np.tile(np.random.rand(5), (5,1))*4
a,b,c

(array([[0.61262529, 2.07465036, 0.10080633, 3.73174969, 0.94478709],
        [3.48873929, 1.13254649, 3.94305869, 0.78771707, 1.58208469],
        [2.7873796 , 0.8821412 , 3.35861666, 2.52200881, 2.31051876],
        [2.0575551 , 0.43185624, 1.92360217, 1.15343053, 2.669028  ],
        [1.82834107, 3.05421588, 0.91119481, 1.01324625, 0.30585594]]),
 array([[1.43606948, 3.32887089, 3.97497756, 1.61091354, 2.25120925],
        [1.60027538, 0.95382023, 2.96848578, 1.65400964, 2.45578788],
        [1.82963009, 3.98493421, 1.04861007, 0.88142668, 2.7844102 ],
        [0.0523341 , 2.60156112, 2.41067462, 3.69129415, 3.78179874],
        [2.25489612, 0.24207099, 3.65859799, 1.59240835, 0.59392839]]),
 array([[2.78476877, 1.49472526, 0.58944439, 3.11801272, 0.23342245],
        [2.78476877, 1.49472526, 0.58944439, 3.11801272, 0.23342245],
        [2.78476877, 1.49472526, 0.58944439, 3.11801272, 0.23342245],
        [2.78476877, 1.49472526, 0.58944439, 3.11801272, 0.23342245],
        [2.78476

In [23]:
a = np.ones((10, 10))
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [24]:
a = np.zeros((8, 8), dtype=int)
a[1::2, ::2] = 1
a[::2, 1::2] = 1
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [25]:
a = np.random.random(30)
mean_value = np.mean(a)
a,mean_value

(array([0.91331834, 0.71185141, 0.64956482, 0.13807872, 0.99603737,
        0.18883358, 0.83281418, 0.06336494, 0.44173096, 0.46037444,
        0.15718137, 0.66659361, 0.11314099, 0.43035919, 0.32600958,
        0.64514609, 0.74386522, 0.14700204, 0.06005644, 0.06365672,
        0.39084019, 0.23620874, 0.07965207, 0.18303615, 0.43004614,
        0.67448778, 0.12614121, 0.10860089, 0.20347232, 0.05684435]),
 0.3746103286885401)

In [26]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
a = np.arange(24).reshape(2,3,4)
a[ : , :-2:-2, 1::-2]

array([[[ 9]],

       [[21]]])

In [4]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])