## 规范化

In [22]:
from sklearn import datasets
from sklearn import preprocessing
import pandas as pd
import numpy as np
# boston = datasets.load_boston()
# print(boston.feature_names)
# print(boston.target)
# df= pd.DataFrame(boston.data[:, 4:7])
# df.columns = boston.feature_names[4:7]
# print(df)
# The Boston housing prices dataset has an ethical problem
# `load_boston` has been removed from scikit-learn since version 1.2.

In [23]:
# 读取数据data\boston.xlsx
file1 = './data/boston.xlsx'
data = pd.read_excel(file1)
df = data.iloc[:,4:7]
df

,NOX,RM,AGE
0,0.538,6.575,65.2
1,0.469,6.421,78.9
2,0.469,7.185,61.1
3,0.458,6.998,45.8
4,0.458,7.147,54.2
...,...,...,...
501,0.573,6.593,69.1
502,0.573,6.120,76.7
503,0.573,6.976,91.0
504,0.573,6.794,89.3


### 最小-最大规范化
* 若将来的数字超过min和max需重新定义
* 若某个数很大则规范化后值相近且均接近0


In [24]:
# 最小-最大规范化 (df-df.min())/(df.max()-df.min())
min_max_scaler = preprocessing.minmax_scale(df)
print(min_max_scaler)

[[0.31481481 0.57750527 0.64160659]
 [0.17283951 0.5479977  0.78269825]
 [0.17283951 0.6943859  0.59938208]
 ...
 [0.38683128 0.65433991 0.90731205]
 [0.38683128 0.61946733 0.88980433]
 [0.38683128 0.47307913 0.80226571]]


### z-score规范化
* 使用最多
* 处理后数据的均值为0，标准差为1

In [25]:
# z-score规范化 (df-df.mean())/df.std()
z_scaler = preprocessing.scale(df)
print(z_scaler)

[[-0.14421743  0.41367189 -0.12001342]
 [-0.74026221  0.19427445  0.36716642]
 [-0.74026221  1.28271368 -0.26581176]
 ...
 [ 0.15812412  0.98496002  0.79744934]
 [ 0.15812412  0.72567214  0.73699637]
 [ 0.15812412 -0.36276709  0.43473151]]


### 小数定标规范化
* 移动小数点位置，移动位数,取决于属性绝对值的最大值
* 常见落在[-1, 1]之间

In [26]:
# 小数定标规范化
float_scaler = df/10**np.ceil(np.log10(df.abs().max()))
print(float_scaler)


       NOX      RM    AGE
0    0.538  0.6575  0.652
1    0.469  0.6421  0.789
2    0.469  0.7185  0.611
3    0.458  0.6998  0.458
4    0.458  0.7147  0.542
..     ...     ...    ...
501  0.573  0.6593  0.691
502  0.573  0.6120  0.767
503  0.573  0.6976  0.910
504  0.573  0.6794  0.893
505  0.573  0.6030  0.808

[506 rows x 3 columns]


## 连续属性离散化
* 将连续的数值型数据转换为离散的分类值的过程，这在数据分析中非常有用，可以简化模型、揭示数据分布模式或满足某些算法的要求。
### 分箱（binning）：
* 等宽法（数据分布均匀）：把数据按设定的箱数等分
  * 划分：如AGE范围是0-100，则分为0-20, 20-40, 40-60, 60-80, 80-100
  * 参数说明：
    * 第一个参数：要离散化的Series
    * 第二个参数：要分的箱数(或自定义的分界点列表)
    * labels：为每个箱指定标签(这里用0-4表示)
* 等频法（数据分布不均）
  * 每个区间包含近似相同数量的观测值，以分位数为边界划分
### 聚类

In [27]:
pd.cut(df.AGE, 5, labels = range(5))  

0      3
1      3
2      2
3      2
4      2
      ..
501    3
502    3
503    4
504    4
505    4
Name: AGE, Length: 506, dtype: category
Categories (5, int64): [0 < 1 < 2 < 3 < 4]

In [28]:
pd.qcut(df.AGE, 5, labels = range(5))

0      1
1      2
2      1
3      1
4      1
      ..
501    2
502    2
503    3
504    3
505    2
Name: AGE, Length: 506, dtype: category
Categories (5, int64): [0 < 1 < 2 < 3 < 4]