## 实验02   numpy数组的创建和切片
1、创建一个3x3 的单位矩阵。
2、创建一个3x3 并且值从0 到8 的矩阵。
3、创建一个5x5 的矩阵，其中每行的数值范围从0到4。 
4、创建一个 10x10 的二维数组，并使得边界为1，中间全为0 。
5、	创建一个8*8 的“棋盘”矩阵。
6、创建一个长度为30的随机向量并找到它的平均值。
7、创建一个长度为10 并且除了第五个值为1 的空向量。



1、创建一个3x3 的单位矩阵。

In [49]:
import numpy as np
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [51]:
Z = np.identity(3,int)  #np.eye 更灵活，可以生成非方阵或偏移对角线（例如 np.eye(3, 4, k=1) 生成 3×4 矩阵，且对角线向右偏移 1 列）。
print(Z)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


2、创建一个3x3 并且值从0 到8 的矩阵。

In [6]:
import numpy as np
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3、创建一个5x5 的矩阵，其中每行的数值范围从0到4。 

In [22]:
import numpy as np
Z = np.zeros((5,5),dtype = int)
Z += np.arange(5)
print (Z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [29]:
Z = np.full([5,5],np.arange(5))
print (Z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [32]:
Z = np.tile(np.arange(5),(5,1)) 
print (Z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [38]:
Z = np.array([np.arange(5) for i in range(5)])
print (Z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### 4、创建一个 10x10 的二维数组，并使得边界为1，中间全为0 。

In [23]:
import numpy as np
x=np.ones((10,10),dtype = int)
x[1:-1,1:-1]=0
print (x)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [33]:
Z = np.full([10,10],1)
Z[1:9,1:9]=0
print (Z)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [41]:
Z = np.ones((10,10),dtype = int)
for i in range(1,9):
    for j in range(1,9):
        Z[i,j]=0
print(Z)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


5、创建一个8*8 的“棋盘”矩阵。

In [11]:
 import numpy as np
z=np.zeros((8,8),dtype=int)
z[1::2,::2]=1    #1、3、5、7 行 ；0 、2、4、6 列的元素置为1
z[::2,1::2]=1
print (z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [34]:
Z = np.full([10,10],0)
Z[1::2,::2]=1
Z[::2,1::2]=1
print (Z)

[[0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]]


In [12]:
Z=np.tile([[0,1],[1,0]],(4,4))  # np.tile函数可以将原矩阵横向或纵向铺开
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [47]:
Z = np.zeros((8,8),dtype=int)
for i in range(8):
    for j in range(8):
        if(i+j)%2==1:
            Z[i,j]=1
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


6、创建一个长度为30的随机向量并找到它的平均值。

In [26]:
import numpy as np
Z = np.random.random(30)
m = Z.mean()
print(Z)
print("平均值:",m)

[0.25001373 0.9782535  0.67713364 0.32182662 0.98571348 0.26792868
 0.88476833 0.65388644 0.27976863 0.02843573 0.36300729 0.25612271
 0.71312778 0.47644075 0.86775321 0.65679839 0.48445045 0.38205652
 0.72824867 0.80257403 0.16309282 0.36426566 0.94245067 0.47600361
 0.75926575 0.15442846 0.25893128 0.70085309 0.84135827 0.93381985]
平均值: 0.5550926020956399


7、创建一个长度为10 并且除了第五个值为1 的空向量。

In [25]:
import numpy as np
Z = np.zeros(10,dtype = int)
Z[4] = 1
print(Z)

[0 0 0 0 1 0 0 0 0 0]
